// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6J8CN2kpJSAOo3EETYk74DK4XM_xTj0',
    appId: '1:462444646789:web:f0fdfa25decad72d08b4ec',
    messagingSenderId: '462444646789',
    projectId: 'indokos-app',
    authDomain: 'indokos-app.firebaseapp.com',
    storageBucket: 'indokos-app.firebasestorage.app',
    measurementId: 'G-0T29ZYJ1JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqL_XAXC1564WBTC9QH61RIzXRv9qa4Zc',
    appId: '1:462444646789:android:0d3f1e35d34cbd3b08b4ec',
    messagingSenderId: '462444646789',
    projectId: 'indokos-app',
    storageBucket: 'indokos-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9I3fZvKIbklDDNsq7J0wNssK6PLHCBfw',
    appId: '1:462444646789:ios:88707675c5e3c02c08b4ec',
    messagingSenderId: '462444646789',
    projectId: 'indokos-app',
    storageBucket: 'indokos-app.firebasestorage.app',
    iosBundleId: 'com.example.indokos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9I3fZvKIbklDDNsq7J0wNssK6PLHCBfw',
    appId: '1:462444646789:ios:88707675c5e3c02c08b4ec',
    messagingSenderId: '462444646789',
    projectId: 'indokos-app',
    storageBucket: 'indokos-app.firebasestorage.app',
    iosBundleId: 'com.example.indokos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg6J8CN2kpJSAOo3EETYk74DK4XM_xTj0',
    appId: '1:462444646789:web:ccd26a532276467208b4ec',
    messagingSenderId: '462444646789',
    projectId: 'indokos-app',
    authDomain: 'indokos-app.firebaseapp.com',
    storageBucket: 'indokos-app.firebasestorage.app',
    measurementId: 'G-RNWHRWDM82',
  );
}
