import 'package:indokos/models/kos_model.dart';
import 'package:indokos/models/booking_model.dart';

final mockKosList = [
  Kos(
    id: '1',
    name: 'Kost Bapak',
    location: 'Talang Kelapa, Palembang',
    price: 1000000,
    rating: 4.5,
    reviewers: 100,
    facilities: ['KM Dalam', 'AC', 'Wifi', 'Parkir'],
    description:
        'Kost yang nyaman dengan fasilitas lengkap di pusat kota Palembang.',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    ],
    type: 'bulanan',
  ),
  Kos(
    id: '2',
    name: 'Kost Buriga',
    location: 'Ilir Timur II, Palembang',
    price: 500000,
    rating: 4.2,
    reviewers: 50,
    facilities: ['KM Dalam', 'Wifi', 'Parkir'],
    description: 'Kost ekonomis dengan lokasi strategis dekat kampus.',
    images: [
      'https://images.unsplash.com/photo-1554469384-e58fac16e23a?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      'https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg?auto=compress&cs=tinysrgb&w=500',
    ],
    type: 'bulanan',
  ),
  Kos(
    id: '3',
    name: 'Bambang Kost',
    location: 'Jakabaring, Palembang',
    price: 800000,
    rating: 4.2,
    reviewers: 75,
    facilities: ['KM Dalam', 'AC', 'Parkir', 'Dapur'],
    description: 'Kost dengan suasana asri dan lingkungan yang tenang.',
    images: [
      'https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', // Living room
      'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', // Bedroom
      'https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', // Kitchen area
    ],
    type: 'tahunan',
  ),
  Kos(
    id: '4',
    name: 'Kost Putra Palembang',
    location: 'Pahlawan, Palembang',
    price: 1200000,
    rating: 4.2,
    reviewers: 120,
    facilities: ['KM Dalam', 'AC', 'Wifi', 'Parkir', 'Laundry'],
    description: 'Kost eksklusif untuk putra dengan fasilitas premium.',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=500',
    ],
    type: 'tahunan',
  ),
  Kos(
    id: '5',
    name: 'Kost Alfa',
    location: 'Celentang, Palembang',
    price: 900000,
    rating: 4.1,
    reviewers: 60,
    facilities: ['KM Dalam', 'Wifi', 'Parkir', 'Dapur'],
    description: 'Kost modern dengan desain minimalis dan nyaman.',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      //'https://images.unsplash.com/photo-1523357580085-5fef0a4fda6e?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    ],
    type: 'bulanan',
  ),
  Kos(
    id: '6',
    name: 'Kost Aisyah Palembang',
    location: 'Plaju, Palembang',
    price: 1000000,
    rating: 4.5,
    reviewers: 100,
    facilities: ['KM Dalam', 'TV', 'Lemari', 'Tempat Tidur'],
    description: 'Kost khusus wanita dengan keamanan 24 jam.',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      'https://images.pexels.com/photos/279719/pexels-photo-279719.jpeg?auto=compress&cs=tinysrgb&w=500',
    ],
    type: 'bulanan',
  ),
  Kos(
    id: '7',
    name: 'Kost Sweet',
    location: 'Plaju, Palembang',
    price: 1000000,
    rating: 4.5,
    reviewers: 100,
    facilities: ['KM Dalam', 'AC', 'Wifi', 'Parkir'],
    description: 'Kost dengan suasana homey dan pelayanan ramah.',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=500',
    ],
    type: 'bulanan',
  ),
  Kos(
    id: '8',
    name: 'Kost Harmoni',
    location: 'Kemuning, Palembang',
    price: 750000,
    rating: 4.0,
    reviewers: 80,
    facilities: ['KM Dalam', 'Kipas Angin', 'Parkir', 'Dapur Bersama'],
    description: 'Kost dengan lokasi strategis dekat pusat perbelanjaan.',
    images: [
      'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      'https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?auto=compress&cs=tinysrgb&w=500',
    ],
    type: 'bulanan',
  ),
  Kos(
    id: '9',
    name: 'Kost Pelangi',
    location: 'Sekip, Palembang',
    price: 850000,
    rating: 4.3,
    reviewers: 65,
    facilities: ['KM Dalam', 'AC', 'Parkir', 'Ruang Tamu'],
    description: 'Kost dengan desain warna-warni yang ceria dan nyaman.',
    images: [
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=500',
    ],
    type: 'tahunan',
  ),
  Kos(
    id: '10',
    name: 'Kost Sejahtera',
    location: 'Kertapati, Palembang',
    price: 600000,
    rating: 3.9,
    reviewers: 45,
    facilities: ['KM Luar', 'Kipas Angin', 'Parkir'],
    description: 'Kost ekonomis dengan lingkungan yang asri dan bersih.',
    images: [
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
      'https://images.pexels.com/photos/271643/pexels-photo-271643.jpeg?auto=compress&cs=tinysrgb&w=500',
    ],
    type: 'bulanan',
  ),
];

final mockBookings = [
  Booking(
    id: '1',
    kosId: '6',
    kosName: 'Kost Aisyah Palembang',
    location: 'Palembang, Sumatra Selatan',
    startDate: DateTime(2022, 1, 1),
    endDate: DateTime(2023, 1, 1),
    status: 'Selesai',
    totalPrice: 12000000,
    paymentMethod: 'Bank Transfer',
  ),
  Booking(
    id: '2',
    kosId: '6',
    kosName: 'Kost Aisyah Palembang',
    location: 'Palembang, Sumatra Selatan',
    startDate: DateTime(2021, 12, 2),
    endDate: DateTime(2022, 6, 2),
    status: 'Selesai',
    totalPrice: 6000000,
    paymentMethod: 'E-Wallet',
  ),
  Booking(
    id: '3',
    kosId: '6',
    kosName: 'Kost Aisyah Palembang',
    location: 'Palembang, Sumatra Selatan',
    startDate: DateTime(2021, 6, 30),
    endDate: DateTime(2021, 7, 30),
    status: 'Selesai',
    totalPrice: 1000000,
    paymentMethod: 'Bank Transfer',
  ),
  Booking(
    id: '4',
    kosId: '6',
    kosName: 'Kost Aisyah Palembang',
    location: 'Palembang, Sumatra Selatan',
    startDate: DateTime(2021, 5, 28),
    endDate: DateTime(2021, 6, 28),
    status: 'Selesai',
    totalPrice: 1000000,
    paymentMethod: 'Bank Transfer',
  ),
  Booking(
    id: '5',
    kosId: '6',
    kosName: 'Kost Aisyah Palembang',
    location: 'Palembang, Sumatra Selatan',
    startDate: DateTime(2021, 1, 1),
    endDate: DateTime(2021, 3, 1),
    status: 'Selesai',
    totalPrice: 2000000,
    paymentMethod: 'Bank Transfer',
  ),
];
